---
- hosts: all
  tasks:
  - name: Install Apps
    win_chocolatey:
      name: '{{ item }}'
      state: present 
    with_items:
    - notepadplusplus
    - putty
    - microsoft-edge
    - microsoft-monitoring-agent
    
