---
- name: " Windows TimeZone"
  hosts: all
  tasks:
    - name: "Set the TimeZone"
      win_timezone:
         timezone: "GMT Standard Time" 
         
- name: " Set the region format to English GB"
  hosts: all
  tasks:
    - name: "Set the Region"
      community.windows.win_region:
        format: en-GB
